// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  welcomeSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {type: 'link', label: 'DUNE', href: '/DUNE/latest/', },
  ],
};

module.exports = sidebars;
