// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  welcomeSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'Manuals',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'nodeos',
          href: '/leap/latest/nodeos/'
        },
        {
          type: 'link',
          label: 'cleos',
          href: '/leap/latest/cleos/'
        },
        {
          type: 'link',
          label: 'keosd',
          href: '/leap/latest/keosd/'
        },
        {
          type: 'link',
          label: 'CDT',
          href: '/cdt/latest/'
        },
        {
          type: 'link',
          label: 'System Contracts',
          href: '/system-contracts/latest/'
        },
      ],
    },
    {type: 'link', label: 'DUNE', href: '/DUNE/latest/', },
  ],
};

module.exports = sidebars;
